@startuml
'https://plantuml.com/class-diagram

!include lexakai.theme

title "Fiasco"

top to bottom direction

'=============================================
' Dependencies
'=============================================

package fiasco.dependencies
{
    '=============================================
    ' Dependencies
    '=============================================

    interface Dependency
    class DependencyGraph
    class Library

    Library -u-|> Dependency
    DependencyGraph "*" o-r- "1" Dependency : "    contains    "
}

'=============================================
' Repository
'=============================================

package fiasco.repository
{
    interface Repository
    interface Artifact

    class MavenRepository
    MavenRepository -u-|> Repository
    MavenRepository "1" o-- "*" MavenGroup : "contains                  "

    '=============================================
    ' Artifacts
    '=============================================

    class MavenArtifact
    class MavenGroup
    class Version

    MavenArtifact -u---|> Artifact
    MavenArtifact o-l- Version
    Library o-- MavenArtifact : "is       "
    Library "1" o-- "*" MavenArtifact : "excludes"
    MavenGroup "1" o-- "*" MavenArtifact : "contains"
}


'=============================================
' Tools
'=============================================

package fiasco.tools
{
    interface Tool
}

'=============================================
' Module
'=============================================

package fiasco.module
{
    class Module

    Module -r-|> Dependency
    Module "1" o-- "*" Module : "depends on"
    Module "1" o---- "*" Tool : "builds with"
}

'=============================================
' Projects
'=============================================

package fiasco.project.metadata
{
    interface ProjectMetadata

    class Copyright
    class WebSite
    class License
    class Organization
    class Contributor

    Contributor "1" o-r- "*" Organization : " belongs to "
    ProjectMetadata o-- Copyright
    ProjectMetadata "1" o-l- "*" WebSite : "  documented on  "
    ProjectMetadata "1" o-- "*" Contributor : "developed by"
    ProjectMetadata o-r- Organization : "originated by"
    ProjectMetadata "1" o-- "*" License : "distributed under"
}

package fiasco.project
{
    interface Project

    Project o--- ProjectMetadata : "     described by"
}

'=============================================
' Build
'=============================================

package fiasco.build
{
    interface Builder
    interface Buildable
    interface BuildListener

    class Build
    class BuildPlanner

    Module -u--|> Buildable
    Build -r-> Builder : "    builds with                       "
    Build "1" o-u- "*" Project : "    finds modules in"
    Build o-- BuildPlanner : "   plans build with"
    BuildPlanner ---> DependencyGraph : "creates"

    Builder "1" o-d- "*" Buildable : "    builds    "
    Builder --> BuildListener : "notifies"
}

package fiasco
{
    class Fiasco

    Fiasco "1" o-d- "*" Build : "    performs"
}

package fiasco.build.builders
{
    class ParallelBuilder
    class RemoteBuilder

    ParallelBuilder -u-|> Builder
    RemoteBuilder -u-|> Builder
}

'=============================================
' File Tools
'=============================================

package fiasco.tools.file
{
    interface FileTool
    FileTool -u-|> Tool

    class FileCopier
    class FileRemover
    class JavaPackager
    class ProjectVersionUpdater
    class BuildVersionUpdater

    FileRemover           -u-|> FileTool
    FileCopier            -u-|> FileTool
    ProjectVersionUpdater -u--|> FileTool
    BuildVersionUpdater   -u---|> FileTool
    JavaPackager          -u---|> FileTool
}

'=============================================
' JAR and Archive Tools
'=============================================

package fiasco.tools.jar
{
    interface JarTool
    JarTool -u----|> FileTool

    class JarArchiver
    class JarShader
    class JarSigner
    class JarManifestUpdater

    JarArchiver        -u-|> JarTool
    JarShader          -u-|> JarTool
    JarSigner          -u--|> JarTool
    JarManifestUpdater -u--|> JarTool
}

'=============================================
' JAR and Archive Tools
'=============================================

package fiasco.tools.repository
{
    interface RepositoryTool
    RepositoryTool -u----|> FileTool

    class Librarian

    Librarian -u--|> RepositoryTool
}

'=============================================
' Compiler Tools
'=============================================

package fiasco.tools.compiler
{
    interface Compiler
    Compiler -u---|> FileTool

    class AntlrCompiler
    class GrpcCompiler
    class JavaCompiler
    class JavadocCompiler
    class LexakaiCompiler
    class ProtobufCompiler

    AntlrCompiler    -u-|> Compiler
    GrpcCompiler     -u-|> Compiler
    JavaCompiler     -u--|> Compiler
    JavadocCompiler  -u--|> Compiler
    LexakaiCompiler  -u---|> Compiler
    ProtobufCompiler -u---|> Compiler
}

'=============================================
' Network Tools
'=============================================

package fiasco.tools.network
{
    interface NetworkTool
    NetworkTool  -u--|> Tool

    class Librarian
    class Publisher
    class Deployer
    class RemoteCopier

    Librarian    -u-|> NetworkTool
    Deployer     -u-|> NetworkTool
    Publisher    -u-|> NetworkTool
    RemoteCopier -u-|> NetworkTool
}

'=============================================
' Test Tools
'=============================================

package fiasco.tools.test
{
    interface TestTool
    TestTool -u---> Tool

    class JUnit

    JUnit -u-|> TestTool
}

@enduml
